---
- name: Destroy
  hosts: all
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Remove VM from VMware
      vmware_guest:
        validate_certs: no
        name: "{{ inventory_hostname }}"
        state: absent
        datacenter: demolab
        force: yes
      delegate_to: localhost

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
